name: Continuous Delivery (Docker)

on:
  push:
    branches:
      - main
    paths:
      - "logic/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: vinimrs
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./logic
          file: ./logic/Dockerfile
          push: true
          tags: vinimrs/mv-bombas-web-logic:latest

  ansible:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setting ssh key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./logic/ansible/continuous-playbook.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # # Optional, literal inventory file contents
          inventory: |
            [mvbombas_logic]
            ${{secrets.SSH_HOST}} ansible_user=ubuntu
          options: |
            --verbose
